name: test-deploy
run-name: nguyen chi cuong 

on: 
  label:
    types:
      - created
  push: 
    branches: [development]
jobs: 

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup ok
        run: echo "set up"
  test: 
    needs: setup
    runs-on: ubuntu-latest
    steps: 
      - run: echo "test"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/setup-node@v3 
        with:
            node-version: ${{ matrix.node }}
      - run: echo 'chay nek'
     
  
