name: test-deploy
run-name: nguyen chi cuong 

on: 
  # label:
  #   types:
  #     - created
  push: 
    branches: [development]
jobs: 
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup ok
        run: echo "set up"
  test: 
    # needs: setup
    runs-on: ubuntu-latest
    steps: 
      - run: echo "test"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2 
      #   with:
      #       node-version: ${{ matrix.node }}
      - run: sh ./github-actions-script.sh
     
  
